### ISSUE TITLE
statistic match

### ISSUE THREAD

**Issue by LGouellec** [mozvip/sports-predictions#9]
Faire une API qui permet de remonter par match le % de personne qui a réalisé un bon pronostic (equipe + resultat), le % de personne qui a réalisé un pronostic moyen(seul l'équipe), le % de personne qui s'est trompé.

La vue est faite

**Comment by mozvip** [comment]
Created /game?gameId
Still some work to do to properly integrate it.

**Comment by LGouellec** [comment]
Work done. Label team integrated. GO Belgium !!! ;)
